### ISSUE TITLE
anonsurf doesn't install problems with .dpkg dependencies

### ISSUE THREAD

**Issue by nyx775** [Und3rf10w/kali-anonsurf#11]
Hi, i'm having problems during the installation; this is the log:
./installer.sh
--2016-11-10 22:25:37--  https://geti2p.net/_static/i2p-debian-repo.key.asc
Risoluzione di geti2p.net (geti2p.net)... 91.143.92.136, 2a02:180:a:65:2456:6542:1101:1010
Connessione a geti2p.net (geti2p.net)|91.143.92.136|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 14455 (14K) [text/plain]
Salvataggio in: "/tmp/i2p-debian-repo.key.asc"

/tmp/i2p-debian-rep 100%[===================>]  14,12K  --.-KB/s    in 0,07s   

2016-11-10 22:25:43 (214 KB/s) - "/tmp/i2p-debian-repo.key.asc" salvato [14455/14455]

OK
Trovato:1 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease
Trovato:2 http://deb.i2p2.no unstable InRelease
Lettura elenco dei pacchetti... Fatto
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
i2p-keyring is already the newest version (2016.10.01).
0 aggiornati, 0 installati, 0 da rimuovere e 1113 non aggiornati.
dpkg-deb: building package 'kali-anonsurf' in 'kali-anonsurf.deb'.
Selezionato il pacchetto kali-anonsurf non precedentemente selezionato.
(Lettura del database... 327632 file e directory attualmente installati.)
Preparativi per estrarre kali-anonsurf.deb...
Estrazione di kali-anonsurf (1.2.1)...
dpkg: problemi con le dipendenze impediscono la configurazione di kali-anonsurf:
 kali-anonsurf dipende da secure-delete; comunque:
  Il pacchetto secure-delete non è installato.
 kali-anonsurf dipende da i2p; comunque:
  Il pacchetto i2p non è installato.

dpkg: errore nell'elaborare il pacchetto kali-anonsurf (--install):
 problemi con le dipendenze - lasciato non configurato
Elaborazione dei trigger per systemd (231-4)...
Si sono verificati degli errori nell'elaborazione:
 kali-anonsurf
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Correzione delle dipendenze... Fatto
Il seguente pacchetto è stato installato automaticamente e non è più richiesto:
  libservice-wrapper-java libservice-wrapper-jni secure-delete service-wrapper
Usare "apt autoremove" per rimuoverlo.
The following additional packages will be installed:
  secure-delete
I seguenti pacchetti saranno RIMOSSI:
  kali-anonsurf
I seguenti pacchetti NUOVI saranno installati:
  secure-delete
0 aggiornati, 1 installati, 1 da rimuovere e 1113 non aggiornati.
1 non completamente installati o rimossi.
È necessario scaricare 0 B/69,6 kB di archivi.
Dopo quest'operazione, verranno occupati 94,2 kB di spazio su disco.
Continuare? [S/n] 
Lettura del database... 327640 file e directory attualmente installati.)
Rimozione di kali-anonsurf (1.2.1)...
Selezionato il pacchetto secure-delete non precedentemente selezionato.
(Lettura del database... 327632 file e directory attualmente installati.)
Preparativi per estrarre .../secure-delete_3.1-6_amd64.deb...
Estrazione di secure-delete (3.1-6)...
Configurazione di secure-delete (3.1-6)...
Elaborazione dei trigger per systemd (231-4)...
Elaborazione dei trigger per man-db (2.7.5-1)...
Selezionato il pacchetto kali-anonsurf non precedentemente selezionato.
(Lettura del database... 327649 file e directory attualmente installati.)
Preparativi per estrarre kali-anonsurf.deb...
Estrazione di kali-anonsurf (1.2.1)...
dpkg: problemi con le dipendenze impediscono la configurazione di kali-anonsurf:
 kali-anonsurf dipende da i2p; comunque:
  Il pacchetto i2p non è installato.

dpkg: errore nell'elaborare il pacchetto kali-anonsurf (--install):
 problemi con le dipendenze - lasciato non configurato
Elaborazione dei trigger per systemd (231-4)...
Si sono verificati degli errori nell'elaborazione:
 kali-anonsurf

please help me, thanks.

**Comment by Und3rf10w** [comment]
Uhhhh.... So I don't read Italian. That being said, I'll give this a shot with some help from Google Translate. If possible, please provide logs in English. However, I do appreciate you providing the logs regardless, that helps me out a lot.

Based on the logs, it appears to me that the ```i2p``` package didn't install for some reason. It should have attempted to install it as a dependency within the installer, but I'll modify the installer to install the dependencies before hand.

In the mean time, as a quick fix, can you run the following?

```bash
apt-get update
apt-get install i2p
apt-get install kali-anonsurf
```

**Comment by Und3rf10w** [comment]
This should be fixed by #12. Please pull the lastest copy of kali-anonsurf and rerun the installer.

```bash
git clone https://github.com/Und3rf10w/kali-anonsurf.git
cd kali-anonsurf
./installer
```

Please reopen this issue if you continue to experience problems.

**Comment by Resire** [comment]
OK I have tried everything to make this work. I had Kali Linux duel booted with Windows 10 and it did not work first of all 2nd I even reinstalled Kali Linux on my other HDD which had nothing on it and then tried anonsurf again and it didnt work I have looked everywhere and really need help why this is not working.

root@kali:~# git clone https://github.com/Und3rf10w/kali-anonsurf.git
Cloning into 'kali-anonsurf'...
remote: Counting objects: 301, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 301 (delta 5), reused 0 (delta 0), pack-reused 278
Receiving objects: 100% (301/301), 170.36 KiB | 0 bytes/s, done.
Resolving deltas: 100% (86/86), done.
Checking connectivity... done.
root@kali:~# ls -l
total 36
drwxr-xr-x 2 root root 4096 Nov 27 13:31 Desktop
drwxr-xr-x 2 root root 4096 Nov 27 13:31 Documents
drwxr-xr-x 2 root root 4096 Nov 27 17:11 Downloads
drwxr-xr-x 4 root root 4096 Nov 27 17:11 kali-anonsurf
drwxr-xr-x 2 root root 4096 Nov 27 13:31 Music
drwxr-xr-x 2 root root 4096 Nov 27 13:31 Pictures
drwxr-xr-x 2 root root 4096 Nov 27 13:31 Public
drwxr-xr-x 2 root root 4096 Nov 27 13:31 Templates
drwxr-xr-x 2 root root 4096 Nov 27 13:31 Videos
root@kali:~# cd kali-anonsurf
root@kali:~/kali-anonsurf# ls -l
total 44
-rwxr-xr-x 1 root root  1060 Nov 27 17:11 installer.sh
drwxr-xr-x 5 root root  4096 Nov 27 17:11 kali-anonsurf-deb-src
-rw-r--r-- 1 root root 32472 Nov 27 17:11 LICENSE
-rw-r--r-- 1 root root  1938 Nov 27 17:11 README.md
root@kali:~/kali-anonsurf# sudo ./installer.sh
--2016-11-27 17:12:16--  https://geti2p.net/_static/i2p-debian-repo.key.asc
Resolving geti2p.net (geti2p.net)... 91.143.92.136, 2a02:180:a:65:2456:6542:1101:1010
Connecting to geti2p.net (geti2p.net)|91.143.92.136|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14455 (14K) [text/plain]
Saving to: ‘/tmp/i2p-debian-repo.key.asc’

/tmp/i2p-debian-rep 100%[===================>]  14.12K  46.3KB/s    in 0.3s    

2016-11-27 17:12:18 (46.3 KB/s) - ‘/tmp/i2p-debian-repo.key.asc’ saved [14455/14455]

OK
Hit:2 http://deb.i2p2.no unstable InRelease   
Hit:1 http://kali.mirror.garr.it/mirrors/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
i2p-keyring is already the newest version (2016.10.01).
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 kali-anonsurf : Depends: i2p but it is not going to be installed
                 Recommends: gtkdialog but it is not installable
                 Recommends: gufw but it is not going to be installed
                 Recommends: libnotify-bin but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
Reading package lists... Done
Building dependency tree       
Reading state information... Done
secure-delete is already the newest version (3.1-6).
secure-delete set to manually installed.
tor is already the newest version (0.2.8.9-1).
tor set to manually installed.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 i2p : Depends: i2p-router (>= 0.8.6-5) but it is not going to be installed
       Depends: libjbigi-jni but it is not going to be installed
       Depends: service-wrapper but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
dpkg-deb: building package 'kali-anonsurf' in 'kali-anonsurf.deb'.
(Reading database ... 303660 files and directories currently installed.)
Preparing to unpack kali-anonsurf.deb ...
Unpacking kali-anonsurf (1.2.2) over (1.2.2) ...
dpkg: dependency problems prevent configuration of kali-anonsurf:
 kali-anonsurf depends on i2p; however:
  Package i2p is not installed.

dpkg: error processing package kali-anonsurf (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (231-4) ...
Errors were encountered while processing:
 kali-anonsurf
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  libservice-wrapper-java libservice-wrapper-jni secure-delete service-wrapper
  tor tor-geoipdb torsocks
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  kali-anonsurf
0 upgraded, 0 newly installed, 1 to remove and 1326 not upgraded.
1 not fully installed or removed.
After this operation, 65.5 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 303660 files and directories currently installed.)
Removing kali-anonsurf (1.2.2) ...
Processing triggers for systemd (231-4) ...
Selecting previously unselected package kali-anonsurf.
(Reading database ... 303652 files and directories currently installed.)
Preparing to unpack kali-anonsurf.deb ...
Unpacking kali-anonsurf (1.2.2) ...
dpkg: dependency problems prevent configuration of kali-anonsurf:
 kali-anonsurf depends on i2p; however:
  Package i2p is not installed.

dpkg: error processing package kali-anonsurf (--install):
 dependency problems - leaving unconfigured
Processing triggers for systemd (231-4) ...
Errors were encountered while processing:
 kali-anonsurf
root@kali:~/kali-anonsurf# anonsurf 

Parrot AnonSurf Module
	Usage:
	┌──[root@kali]─[/root/kali-anonsurf]
	└──╼ $ anonsurf {start|stop|restart|change|status}
	
	 start - Start system-wide anonymous
		  tunneling under TOR proxy through iptables	  
	 stop - Reset original iptables settings
		  and return to clear navigation
	 restart - Combines "stop" and "start" options
	 change - Changes identity restarting TOR
	 status - Check if AnonSurf is working properly
	 myip - Show your current IP address
	----[ I2P related features ]----
	 starti2p - Start i2p services
	 stopi2p - Stop i2p services
	

root@kali:~/kali-anonsurf# anonsurf start
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping IPv6 services:


[ i ] Starting anonymous mode:

 * Tor is not running!  starting it  for you

 * Saved iptables rules

 * Modified resolv.conf to use Tor and Private Internet Access DNS
 * All traffic was redirected throught Tor

[ i ] You are under AnonSurf tunnel


root@kali:~/kali-anonsurf# anonsurf myip

My ip is:

curl: (6) Could not resolve host: myexternalip.com


----------------------------------------------------------------------

root@kali:~/kali-anonsurf#
