### ISSUE TITLE
problems with i2p

### ISSUE THREAD

**Issue by nyx775** [Und3rf10w/kali-anonsurf#13]
hi, thanks for the answer and for the update.
I tried to install the new version of kali-anonsurf but he gives this errors:
Selected the package kali-anonsurf not previously selected.
(Lettura del database... 327649 file e directory attualmente installati.)
trying to extract kali-anonsurf.deb...
Extract of kali-anonsurf (1.2.2)...
dpkg: problems with dependencies cannot configure kali-anonsurf:
 kali-anonsurf dipends of i2p; however:
 Package i2p is not installed.

dpkg: errors with package kali-anonsurf (--install)
problems with dependencies - not installed
elaboration  of the triggers for systemd (231-4)...
Some errors in the elaboration:
 kali-anonsurf
 so i tried with:
-apt-get update (ok)
-apt-get install i2p:
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
È utile eseguire "apt-get -f install" per correggere questi problemi:
I seguenti pacchetti hanno dipendenze non soddisfatte:
 i2p : Dipende: i2p-router (>= 0.8.6-5) ma non sta per essere installato
       Dipende: libjbigi-jni ma non sta per essere installato
       Dipende: service-wrapper ma non sta per essere installato
E: Dipendenze non soddisfatte. Provare "apt-get -f install" senza pacchetti (o specificare una soluzione).

- apt-get install kali-anonsurf
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
kali-anonsurf is already the newest version (1.2.2).
È utile eseguire "apt-get -f install" per correggere questi problemi:
I seguenti pacchetti hanno dipendenze non soddisfatte:
 kali-anonsurf : Dipende: i2p ma non sta per essere installato
                 Raccomanda: gtkdialog ma non è installabile
E: Dipendenze non soddisfatte. Provare "apt-get -f install" senza pacchetti (o specificare una soluzione).

so i tried with apt-get install -f
and again with apt-get install i2p
ettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
Alcuni pacchetti non possono essere installati. Questo può voler dire
che è stata richiesta una situazione impossibile oppure, se si sta
usando una distribuzione in sviluppo, che alcuni pacchetti richiesti
non sono ancora stati creati o sono stati rimossi da Incoming.
Le seguenti informazioni possono aiutare a risolvere la situazione:

I seguenti pacchetti hanno dipendenze non soddisfatte:
 i2p : Dipende: i2p-router (>= 0.8.6-5) ma non sta per essere installato
       Dipende: libjbigi-jni ma non sta per essere installato
E: Impossibile correggere i problemi, ci sono pacchetti danneggiati bloccati.

sorry in some cases for the italian

**Comment by Und3rf10w** [comment]
No worries about the Italian, Google translate handles it well.

This appears to be a problem with installing i2p. It looks like you can't install the ```libjbigi-jni``` package.

What distro are you using? Can you provide the output of: 
```bash
uname -a
cat /etc/lsb_release
apt-cache search libjbigi-jni
``` 

You may want to attempt to install the package yourself.

Per the i2p documentation, download the correct deb for your environment.

- amd64: http://deb.i2p2.no/pool/main/i/i2p/libjbigi-jni_0.9.27-1~deb8u+1_amd64.deb
- i386: http://deb.i2p2.no/pool/main/i/i2p/libjbigi-jni_0.9.27-1-1ubuntu1_i386.deb

Attempt to install it via:
```bash
wget -O libjbigi-jni_amd64.deb http://deb.i2p2.no/pool/main/i/i2p/libjbigi-jni_0.9.27-1~deb8u+1_amd64.deb
dpkg -i libjbigi-jni_amd64.deb
````
At this point, you're running into dependency issues with i2p.

**Comment by Und3rf10w** [comment]
Related to #11

**Comment by nyx775** [comment]
yes, thank you.
Linux 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
cat: /etc/lsb_release: File o directory non esistente
libjbigi-jni - Java Big Integer library

downloaded it:
wget -O libjbigi-jni_amd64.deb http://deb.i2p2.no/pool/main/i/i2p/libjbigi-jni_0.9.27-1~deb8u+1_amd64.deb
--2016-11-13 12:26:28--  http://deb.i2p2.no/pool/main/i/i2p/libjbigi-jni_0.9.27-1~deb8u+1_amd64.deb
Risoluzione di deb.i2p2.no (deb.i2p2.no)... 193.150.121.69
Connessione a deb.i2p2.no (deb.i2p2.no)|193.150.121.69|:80... connesso.
Richiesta HTTP inviata, in attesa di risposta... 200 OK
Lunghezza: 4962 (4,8K) [application/x-debian-package]
Salvataggio in: "libjbigi-jni_amd64.deb"

libjbigi-jni_amd64. 100%[===================>]   4,85K  --.-KB/s    in 0s      

2016-11-13 12:26:29 (365 MB/s) - "libjbigi-jni_amd64.deb" salvato [4962/4962]

cannot install:
dpkg -i libjbigi-jni_amd64.deb
Selezionato il pacchetto libjbigi-jni non precedentemente selezionato.
(Lettura del database... 327632 file e directory attualmente installati.)
Preparativi per estrarre libjbigi-jni_amd64.deb...
Estrazione di libjbigi-jni (0.9.27-1~deb8u+1)...
dpkg: problemi con le dipendenze impediscono la configurazione di libjbigi-jni:
 libjbigi-jni dipende da i2p-router; comunque:
  Il pacchetto i2p-router non è installato.

it says it depends on i2p-router
the package i2p router is not installed
 so i try to install it:
apt-get install i2p-router
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
È utile eseguire "apt-get -f install" per correggere questi problemi:
I seguenti pacchetti hanno dipendenze non soddisfatte:
 i2p-router : Dipende: libecj-java ma non sta per essere installato
              Dipende: libgetopt-java ma non sta per essere installato
              Dipende: libjetty8-java ma non è installabile
              Dipende: libservlet3.0-java ma non sta per essere installato
              Dipende: glassfish-javaee ma non sta per essere installato
              Raccomanda: ttf-dejavu ma non sta per essere installato
E: Dipendenze non soddisfatte. Provare "apt-get -f install" senza pacchetti (o specificare una soluzione).

dpkg: errore nell'elaborare il pacchetto libjbigi-jni (--install):
 problemi con le dipendenze - lasciato non configurato
Si sono verificati degli errori nell'elaborazione:
 libjbigi-jni

i tried to install this packages but;
apt-get install libecj-java
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze       
Lettura informazioni sullo stato... Fatto
È utile eseguire "apt-get -f install" per correggere questi problemi:
I seguenti pacchetti hanno dipendenze non soddisfatte:
 libjbigi-jni : Dipende: i2p-router ma non sta per essere installato
E: Dipendenze non soddisfatte. Provare "apt-get -f install" senza pacchetti (o specificare una soluzione).

**Comment by Und3rf10w** [comment]
That's odd.... It's not installing the dependencies for you for some reason. ```apt-get -f install``` should have done that, but it doesn't lkook like it's doing it...

```bash
apt-get update
apt-get install libecj-java libgetopt-java libjetty8-java libservlet3.0-java glassfish-JavaEE tff-dejavu i2p i2p-router
apt-get -f install
```

You can try giving that a go. It doesn't appear to have produced an error to the point where it can't install any of the dependencies yet, so that's a good sign.

**Comment by nyx775** [comment]
i've done a clena install of Kali, but the errors is gonna be present again, i don't know why...
i fixed anonsurf with this:
apt-get update
apt-get install libservlet3.0-java #if this fails, I suggest you start from a fresh Kali install
wget http://ftp.us.debian.org/debian/pool/main/j/jetty8/libjetty8-java_8.1.16-4_all.deb
dpkg -i libjetty8-java_8.1.16-4_all.deb # This should succeed without error
apt-get install libecj-java libgetopt-java libservlet3.0-java glassfish-javaee ttf-dejavu i2p i2p-router #installs i2p and other dependencies
apt-get -f install # resolves anything else in a broken state

thanks a lot, have a good day.

**Comment by Und3rf10w** [comment]
Awesome, glad that helped. That's not a problem with the ```anonsurf```, but it's a problem with the ```i2p``` package. If I receive additional reports of this, I will build a workaround into the package.

**Comment by blackghostt** [comment]
thank you very much
