### ISSUE TITLE
Anonsurf problem

### ISSUE THREAD

**Issue by Alph4-ZeR00** [Und3rf10w/kali-anonsurf#14]
when I stop anonsurf
i open firefox i get info
connection is not establish....
how to fix ??

**Comment by Und3rf10w** [comment]
I'm going to be honest. There's not nearly enough info here for me to even begin to help you. Start with the basics:

- Do you have any iptables rules that are applied before you started anonsurf?
- Is there any reason running the command ```service networking restart``` would break your environment?
- What has changed with your connection settings between when you start and stop anonsurf?
- What does the output of ```uname -a``` display?
- What proxy settings do you have set up for your Firefox? If it isn't setup to either use system settings, or auto-detect proxy settings, you can expect things to break.

**Comment by Alph4-ZeR00** [comment]
1. I Dont Have
2.No
3.nothing 
4. Linux alph4-zer00 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Alph4-ZeR00** [comment]
& How Can I uninstall Anonsurf?

**Comment by Und3rf10w** [comment]
```apt-get remove kali-anonsurf``` should do the trick to uninstall it.

It looks like you're using Ubuntu. Is your name resolution what's failing, or just outbound connections in general? If it's just name resolution, it's likely something with ```resolvconf```

**Comment by Alph4-ZeR00** [comment]
Thanks Bro 
I fixed
Thnaks for helping me
