### ISSUE TITLE
Offending packet error all the time

### ISSUE THREAD

**Issue by blkv0lk** [Und3rf10w/kali-anonsurf#20]
Everytime i run nmap with anonsurf turned on, i get the offending packet issue. I also get it when running proxychains with anonsurf off. I saw in your blogpost that there was a fix by modifying the iptables in /etc/sysconfig. I didn have the folder at first so i created it and added the iptable rules that you mentioned were found in parrotsec. But nothing is working no matter what and i keep getting that error. I made sure that my firewall is turned off too. i cant seem to find out where the problem is or whats causing it. Is there a different place where the iptables are being read from for anonsurf?

Am running ParrotsecOS

**Comment by Und3rf10w** [comment]
If you reread the blog post, you'll see that only TCP CONNECT ```-sT``` scans are supported through TOR. Due to some kind of limitations, other scan types are not. If you're going to nmap over TOR, you MUST use ```-sT```, and not ```-A```. See the last paragraph and code block of [the blogpost](http://und3rf10w.blogspot.com/2015/12/tor-nmap-scanning-and-esuring-they-fail.html). To my knowledge, anonsurf should configure proxychains to support this:

```bash
# proxychains nmap -sT -Pn -v -p 6660,6282 8.8.8.8  
 ProxyChains-3.1 (http://proxychains.sf.net)  
 Starting Nmap 6.49BETA5 ( https://nmap.org ) at 2015-12-01 11:47 EST  
 Initiating Parallel DNS resolution of 1 host. at 11:47  
 Completed Parallel DNS resolution of 1 host. at 11:47, 16.50s elapsed  
 Initiating Connect Scan at 11:47  
 Scanning 8.8.8.8 [2 ports]  
 |S-chain|-&lt;&gt;-127.0.0.1:9050-&lt;&gt;&lt;&gt;-8.8.8.8:6660-<--denied data-blogger-escaped-br="">|S-chain|-&lt;&gt;-127.0.0.1:9050-&lt;&gt;&lt;&gt;-8.8.8.8:6282-<--denied data-blogger-escaped-br="">Completed Connect Scan at 11:47, 0.55s elapsed (2 total ports)  
 Nmap scan report for 8.8.8.8  
 Host is up (0.27s latency).  
 PORT   STATE SERVICE  
 6282/tcp closed unknown  
 6660/tcp closed unknown  
 Read data files from: /usr/bin/../share/nmap  
 Nmap done: 1 IP address (1 host up) scanned in 17.09 seconds  ```

**Comment by blkv0lk** [comment]
alright im not getting those offending packet errors anymore but am now receving adjust_timeouts. my server has 4 ports open but the scan is showing that they are closed. i used only -sT and -p flags with proxychains. If i dont use proxychains, the scan shows me a list of 1000 open ports. im not getting accurate readings no matter what kind of flags i use. I would of course prefer to use -sS too but i see that it wont work. If i run the distro live off usb, everything works flawlessly and even though that would be a better choice right now, id like to make sure my system can also run it perfectly. I didnt make any changes regarding my iptables either. Everything in that category is the same since i installed the os. Can you give me any advice as to what can be causing the issue?

**Comment by Und3rf10w** [comment]
I can't really be of much help here unfortunately. I generally recommend against doing portscans over tor. The TCP connect scan is the slowest scan, it's generally the easiest to detect, it's also usually not 100% anonymous. The iptables rules do their best to mitigate this.

Also, if you're attempting to scan your own real ip address as a test, you're going to receive inaccurate results regardless. It's better to test using ```scanme.nmap.org```.

Examples below limited to 10 ports for brevity:

```bash
# Scan with anonsurf started:
nmap -sT -Pn -v --top-ports 10 scanme.nmap.org

Host is up (0.00043s latency).
PORT     STATE SERVICE
21/tcp   open  ftp
22/tcp   open  ssh
23/tcp   open  telnet
25/tcp   open  smtp
80/tcp   open  http
110/tcp  open  pop3
139/tcp  open  netbios-ssn
443/tcp  open  https
445/tcp  open  microsoft-ds
3389/tcp open  ms-wbt-server

Nmap done: 1 IP address (1 host up) scanned in 17.20 seconds

# Scan with proxychains and anonsurf started:
proxychains nmap -sT -Pn --top-ports 10 45.33.32.156

Nmap scan report for 45.33.32.156
Host is up (1.00s latency).
PORT     STATE  SERVICE
21/tcp   closed ftp
22/tcp   open   ssh
23/tcp   closed telnet
25/tcp   closed smtp
80/tcp   open   http
110/tcp  closed pop3
139/tcp  closed netbios-ssn
443/tcp  closed https
445/tcp  closed microsoft-ds
3389/tcp closed ms-wbt-server

Nmap done: 1 IP address (1 host up) scanned in 31.36 seconds

# Scan with anonsurf disabled:
proxychains nmap -sT -Pn --top-ports 10 45.33.32.156

Nmap scan report for scanme.nmap.org (45.33.32.156)
Host is up (0.69s latency).
PORT     STATE  SERVICE
21/tcp   closed ftp
22/tcp   open   ssh
23/tcp   closed telnet
25/tcp   closed smtp
80/tcp   open   http
110/tcp  closed pop3
139/tcp  closed netbios-ssn
443/tcp  closed https
445/tcp  closed microsoft-ds
3389/tcp closed ms-wbt-server

Nmap done: 1 IP address (1 host up) scanned in 11.11 seconds
```

**Comment by windom3arle** [comment]
> Everytime i run nmap with anonsurf turned on, i get the offending packet issue. I also get it when running proxychains with anonsurf off. I saw in your blogpost that there was a fix by modifying the iptables in /etc/sysconfig. I didn have the folder at first so i created it and added the iptable rules that you mentioned were found in parrotsec. But nothing is working no matter what and i keep getting that error. I made sure that my firewall is turned off too. i cant seem to find out where the problem is or whats causing it. Is there a different place where the iptables are being read from for anonsurf?
> 
> Am running ParrotsecOS

I need help for the same issue. I’ve read the blogpost but I’m not sure where I’ve to past that iptables rule...I’ve got no etc/sysconfig in my Kali version too: must I create that folder and then a file within it called iptables where to paste the iptable rule from the blog?
Thank you for your time!
