### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by FreakOrder** [Und3rf10w/kali-anonsurf#23]
Hello,

I know it should be very easy to install. The only problem that I have is that it says cleaning some dangerous cache elementsgrep: /etc/default/tor: is a register (its translated so sry) and then 

! Please add the following to your /etc/default/tor and restart service:

and I don´t know how to fix this :/

Thank you for your help

**Comment by Und3rf10w** [comment]
I've actually never paid attention to that part of the script. That's an easy thing to automate, so I'll update the script soon.

Please attempt to run the following as root:
```bash
echo 'RUN_DAEMON="yes"' >> /etc/default/tor
```
Then attempt to use it again and let me know whether it works now.

Out of curiosity, what do you get from running ```uname -a```?

**Comment by FreakOrder** [comment]
Thank you for your fast answer.

I am running every command as root and when I ran the line you said, it says bash: /etc/default/tor: is a register
When I delete the folder etc/default/tor it will start but then the message come failed to start tor.service: Unit tor.service not found and then I have no internet connection.

When I type uname -a -> Linux Kali 4.6.0-kali-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

Thank you for your answer

**Comment by FreakOrder** [comment]
I already have the solution but thank you for your help.
I reinstall kali linux and directly install tor and then it worked.

**Comment by digitalnaSRB** [comment]
Hello, 
I have a same problem. 
Also, I have add the line echo 'RUN_DAEMON="yes"' >> /etc/default/tor  
After that anonsurf started but tor can not be open.

 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping IPv6 services:


[ i ] Starting anonymous mode:

 * Tor is not running!  starting it  for you

Failed to start tor.service: Unit tor.service not found.
 * Modified resolv.conf to use Tor and Private Internet Access DNS
iptables v1.6.0: owner: Bad value for "--uid-owner" option: "debian-tor"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.0: owner: Bad value for "--uid-owner" option: "debian-tor"
Try `iptables -h' or 'iptables --help' for more information.
iptables v1.6.0: owner: Bad value for "--uid-owner" option: "debian-tor"
Try `iptables -h' or 'iptables --help' for more information.
 * All traffic was redirected throught Tor

[ i ] You are under AnonSurf tunnel

Also, when anonsurf start I lost connection.

Is it there any help about this.
Thanks a lot!

**Comment by Und3rf10w** [comment]
Looks like ```tor``` didn't install properly for some reason.

Please try to install tor via ```apt-get install tor```

**Comment by digitalnaSRB** [comment]
I am sorry for delay...

Work like a charm.

Great job and thank you so much one more time!

**Comment by mynameisSAL** [comment]
I have same Problem. Please help me. Show me another way to install anonsurf

**Comment by 007kil** [comment]
pls im having the same problem and have installed it several times 
still not work so i need your help
