### ISSUE TITLE
DNS Resolving issue

### ISSUE THREAD

**Issue by N3tw0rk3r** [Und3rf10w/kali-anonsurf#28]
I am using kali linux and after running anonsurf i can't reach internet  by names  but i can ping any IP

root@kali:~# anonsurf start
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping IPv6 services:

[ i ] Starting anonymous mode:

 * Tor is not running!  starting it  for you

 * Saved iptables rules

 * Modified resolv.conf to use Tor and Private Internet Access DNS
 * All traffic was redirected throught Tor

[ i ] You are under AnonSurf tunnel

> 
> root@kali:~# cat /etc/resolv.conf   <== ( I used 127.0.0.1 and without it, same result!)
> nameserver 209.222.18.222
> nameserver 209.222.18.218

> root@kali:~# nslookup google.com
> ;; connection timed out; no servers could be reached

> root@kali:~# ping 209.22.18.222
> PING 209.22.18.222 (209.22.18.222) 56(84) bytes of data.
> 64 bytes from 209.22.18.222: icmp_seq=1 ttl=64 time=0.090 ms
> 64 bytes from 209.22.18.222: icmp_seq=2 ttl=64 time=0.082 ms
> 64 bytes from 209.22.18.222: icmp_seq=3 ttl=64 time=0.089 ms

> root@kali:~# iptables -L
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination         
> 
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination         
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination         
> ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
> ACCEPT     all  --  anywhere             192.168.0.0/16      
> ACCEPT     all  --  anywhere             172.16.0.0/12       
> ACCEPT     all  --  anywhere             10.0.0.0/8          
> ACCEPT     all  --  anywhere             loopback/8          
> ACCEPT     all  --  anywhere             anywhere             owner UID match debian-tor
> REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Any ideas??

**Comment by Und3rf10w** [comment]
What is the output of the following commands, starting with anonsurf being stopped?

```bash
nslookup google.com 8.8.8.8
nslookup google.com 209.222.18.222
anonsurf start
nslookup google.com 8.8.8.8
nslookup google.com 209.222.18.222
echo "nameserver 8.8.8.8" > /etc/resolv.conf
nslookup google.com 8.8.8.8
nslookup google.com 209.222.18.222
curl http://213.211.198.62/download/eicar.com.txt
anonsurf stop
```

**Comment by N3tw0rk3r** [comment]
Thanks Und3rf10w for your replay,
i want to declare that i am pentesting client network and i am supposed to be denied from accessing INTERNET by firewall rules, but after running anonsurf i could bypass that restrictions and reach outside world by IPs only and that is weird so here are the results you asked for:

```
root@kali:~# anonsurf start
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping IPv6 services:


[ i ] Starting anonymous mode:

 * Tor is not running!  starting it  for you

 * Saved iptables rules

 * Modified resolv.conf to use Tor and Private Internet Access DNS
 * All traffic was redirected throught Tor

[ i ] You are under AnonSurf tunnel


root@kali:~# nslookup google.com 8.8.8.8
;; connection timed out; no servers could be reached

root@kali:~# nslookup google.com 209.222.18.222
;; connection timed out; no servers could be reached

root@kali:~# echo "nameserver 8.8.8.8" > /etc/resolv.conf
root@iLap:~# nslookup google.com 8.8.8.8
;; connection timed out; no servers could be reached

root@kali:~# nslookup google.com 209.222.18.222
;; connection timed out; no servers could be reached

root@kali:~# curl http://213.211.198.62/download/eicar.com.txt
curl: (52) Empty reply from server
root@kali:~# ping 213.211.198.62
PING 213.211.198.62 (213.211.198.62) 56(84) bytes of data.
64 bytes from 213.211.198.62: icmp_seq=1 ttl=64 time=0.094 ms
64 bytes from 213.211.198.62: icmp_seq=2 ttl=64 time=0.085 ms
64 bytes from 213.211.198.62: icmp_seq=3 ttl=64 time=0.095 ms
^C
--- 213.211.198.62 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 1998ms
rtt min/avg/max/mdev = 0.085/0.091/0.095/0.009 ms
root@iLap:~# anonsurf stop
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping anonymous mode:

 * Deleted all iptables rules

 * Iptables rules restored

[ i ] Reenabling IPv6 services:

 * Anonymous mode stopped

root@kali:~# 

```

**Comment by Und3rf10w** [comment]
It looks like Tor might be restricted by your client network. Have you tried this on a network that has no known restrictions? This does not appear to be an issue with the application, but rather with the evironment.

**Comment by N3tw0rk3r** [comment]
on network without restrictions some times it works and sometimes it doesn't work with the same previous reasons , so i will install linux-mint and try one more time,
so do you have any ideas how to pass firewall restrictions as long as it's already done by using AnonSurf ?

**Comment by Und3rf10w** [comment]
You would have to use a [tor bridge](https://www.torproject.org/docs/bridges). You can modify the ```/etc/tor/torrc.anon``` file to modify the torrc used by anonsurf. So you'd add the appropriate bridging configuration to that file, then anonsurf will have tor use a bridge.
