### ISSUE TITLE
can`t access to myexternalip.com

### ISSUE THREAD

**Issue by adminlinzi** [Und3rf10w/kali-anonsurf#30]
`root@kali:~# anonsurf myip

My ip is:

211.64.240.238

----------------------------------------------------------------------

root@kali:~# anonsurf start
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping IPv6 services:

[ i ] Starting anonymous mode:

 * Tor is not running!  starting it  for you

 * Saved iptables rules

 * Modified resolv.conf to use Tor and Private Internet Access DNS
 * All traffic was redirected throught Tor

[ i ] You are under AnonSurf tunnel

root@kali:~# anonsurf myip

My ip is:

curl: (6) Could not resolve host: myexternalip.com

----------------------------------------------------------------------

root@kali:~# anonsurf stop
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping anonymous mode:

 * Deleted all iptables rules

 * Iptables rules restored

[ i ] Reenabling IPv6 services:

 * Anonymous mode stopped

root@kali:~# 
root@kali:~# anonsurf myip

My ip is:

211.64.240.238

----------------------------------------------------------------------

root@kali:~# 
`

**Comment by adminlinzi** [comment]
`root@kali:~# ping myexternalip.com
PING myexternalip.com (78.47.139.102) 56(84) bytes of data.
64 bytes from myexternalip.com (78.47.139.102): icmp_seq=1 ttl=128 time=372 ms
64 bytes from myexternalip.com (78.47.139.102): icmp_seq=2 ttl=128 time=498 ms
64 bytes from myexternalip.com (78.47.139.102): icmp_seq=3 ttl=128 time=372 ms
^C
--- myexternalip.com ping statistics ---
4 packets transmitted, 3 received, 25% packet loss, time 3004ms
rtt min/avg/max/mdev = 372.625/414.623/498.335/59.197 ms
root@kali:~# 
`

**Comment by pieterhouwen** [comment]
I found that after reloading Tor you sometimes have to restart the networking service to make DNS work.

You may want to try : service networking restart; anonsurf myip 
If that doesn't work you may want to try ipecho.net : wget -O /tmp/myip http://ipecho.net/plain && cat /tmp/myip

**Comment by Und3rf10w** [comment]
Can you resolve myexternalip.com when tor is running?

**Comment by pieterhouwen** [comment]
Looks like it, but the Private DNS isn't reinstated after reloading tor. Here's some output:

root@supersecretkali:~/# anonsurf start
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping IPv6 services:


[ i ] Starting anonymous mode:

 * Tor is not running!  starting it  for you

 * Saved iptables rules

 * Modified resolv.conf to use Tor and Private Internet Access DNS
 * All traffic was redirected throught Tor

[ i ] You are under AnonSurf tunnel


root@supersecretkali:~/# nslookup myexternalip.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	myexternalip.com
Address: 78.47.139.102

root@supersecretkali:~/# anonsurf change
 * Tor daemon reloaded and forced to change nodes


root@supersecretkali:~/# nslookup myexternalip.com
Server:		209.222.18.222
Address:	209.222.18.222#53

Non-authoritative answer:
Name:	myexternalip.com
Address: 78.47.139.102

root@supersecretkali:~/# anonsurf change
 * Tor daemon reloaded and forced to change nodes


root@supersecretkali:~/# nslookup myexternalip.com
Server:		127.0.0.1
Address:	127.0.0.1#53

Non-authoritative answer:
Name:	myexternalip.com
Address: 78.47.139.102

root@supersecretkali:~/#
