### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by nlee1131** [Und3rf10w/kali-anonsurf#31]
~# proxychains curl 74.125.196.103 |head
ProxyChains-3.1 (http://proxychains.sf.net)
|S-chain|-<>-127.0.0.1:9050-<><>-74.125.196.103:80-<--timeout
curl: (7) Couldn't connect to server

Any help is much appreciated.

**Comment by Und3rf10w** [comment]
Duplicate of #18
