### ISSUE TITLE
Anonsurf and Proxychains.

### ISSUE THREAD

**Issue by yashaizen** [Und3rf10w/kali-anonsurf#33]
I removed tor base and using Anonsurf in place of it. 
I configured my proxychains.conf file and made it dynamic , added socks5 with socks4  for the same ip. 
I launched anonsurf and then used proxychains to make a request. But it stops immediately. Even of the browser is open in background , the terminal shows no status change with proxychains.
Here is a screenshot of the same:
 
![anon](https://user-images.githubusercontent.com/29508944/27426528-9f020ef2-5759-11e7-9286-f2937bc43140.png)

as you can see, the browser is still running in background.  Help me enable and use proxychains properly.

**Comment by Und3rf10w** [comment]
Tor needs to be installed in order for anonsurf to function. At this time, there is no checks being performed as to whether or not it's actually installed after anonsurf is configured.

Please reinstall tor, restart anonsurf, then test by running:
```proxychains curl www.myexternalip.com/raw```

**Comment by yashaizen** [comment]
I installed tor again. Though it was already installed, but I removed it and installed it again . Proxychains curl.. shows that my ip address is changed. It showed the same before, but when I run it in after starting anonsurf as 
"proxychains browsername url" , It opens the browser and  gets closed in the terminal . It does not display any URL activity as it should and gets terminated itself as shown here : 

Websi
![screenshot from 2017-06-24 14-46-47](https://user-images.githubusercontent.com/29508944/27507405-4a30eeae-58ec-11e7-837d-d59157e60fa1.png)

**Anonsurf is running in background before using proxychains(which seems to have no effect at all**
I cannot be sure if I am anonymous while making a "get" request from a server. 
tes do show that my ip is changed and going through tor network with anonsurf. But if anonsurf provides all anonymity, then what is the point of using proxychains to make a request with anonsurf enabled.

**Comment by Und3rf10w** [comment]
Well... You don't have to use proxychains while anonsurf is enabled. I don't think I've documented anywhere that you have to use proxychains. The only thing you would ever use proxychains for is if you wanted a different ip address while anonsurf is enabled, allowing you to technically come from two different tor ip addresses at the same time.

You can verify that your ip changed by doing the following:

```bash
anonsurf stop #basically, just make sure you start doing this with anonsurf off
curl www.myexternalip.com/raw # this is your normal ip address
anonsurf start
curl www.myexternalip.com/raw # this is your tor ip address, all system traffic should be going through here by default without the use of proxychains
proxychains curl www.myexternalip.com/raw # this is a different tor ip address
```

**Comment by yashaizen** [comment]
Wonderful! Thank You Very Much :) 
So basically it means that  "anonsurf" does the task of two commands .. i.e. tor with proxychains by itself.
And we don't even have to mention anonsurf for every request as we do with proxychains? (assuming everything application works under tor network, once enabled)

**Comment by Und3rf10w** [comment]
That is correct. Basically it does this through modification of iptables.
