### ISSUE TITLE
Someone please help : Internet is not working once anonsurf is started. 

### ISSUE THREAD

**Issue by yashaizen** [Und3rf10w/kali-anonsurf#36]
There is a similar issue on this thread but I cannot find any relevant solution there so I am posting a new one. 

I got the same problem ! Everything was working fine, suddenly it stopped. Now its like whenever I start anonsurf , the internet stops. I have gone through the  comments in similar issue posted here. 
I checked that tor browser is working fine. 
I fixed my date and time. 
Resolv.conf file is good. 
The ```curl head``` command returns error 301, document is moved. 
The ```proxychains curl head``` command returns that it needs more proxies. 
That's all I could check. Please help me. It was all working fine and suddenly it stopped. Anonsurf is very important for anything I do.

**Comment by Und3rf10w** [comment]
I believe this is probably related to #18, please view the latest updates in that issue an let me know if that resolves anything for you.

**Comment by yashaizen** [comment]
Hello! The problem is fixed. I started i2p services and the resolv.conf files remains unchanged when I started tor service even after closing i2p . I copied the default resolv.conf file and replaced it with the changed one. Everything works fine now .

**Comment by Und3rf10w** [comment]
I haven't done much testing with the i2p portion, so I have to play around with that some more

**Comment by piyushsharma08** [comment]
Hi, i am getting this error:
![screenshot from 2017-09-04 08-08-04](https://user-images.githubusercontent.com/22920938/30009772-8d181762-9148-11e7-9735-adb852ab14fe.png)
can  anyone please help me out.

**Comment by yashaizen** [comment]
@piyushsharma08  Hey !
Try reinstalling the 'tor' package.
`sudo apt-get install tor -y`

**Comment by piyushsharma08** [comment]
![screenshot from 2017-09-12 22-16-10](https://user-images.githubusercontent.com/22920938/30338113-1a45ca88-9808-11e7-9641-d4a7dd2ab741.png
Actually i never installed tor package.So i tried to install it first ,but as you can see there is error.

**Comment by yashaizen** [comment]
Did you enter the right password? 
and what is the output of your 'sources.list' file?
you can find it here

> /etc/apt/sources.list

**Comment by piyushsharma08** [comment]
![screenshot from 2017-09-12 22-25-11](https://user-images.githubusercontent.com/22920938/30338437-54d0583e-9809-11e7-9d53-055a4c7c8801.png)
ya i have entered my password right.

**Comment by yashaizen** [comment]
Clear everything from 'sources.list' file and replace it by : 

> #deb http://http.kali.org/kali kali-rolling main non-free contrib
>deb http://repo.kali.org/kali kali-rolling main non-free contrib

**Comment by piyushsharma08** [comment]
no it still not working.

**Comment by yashaizen** [comment]
You still can't install 'tor' package? 
If you are using kali , then there was a problem with your 'sources.list' to find the tor repository , but since you have updated it with the proper sources(the one I mentioned above) .. it should work. By the way , I think anonsurf is facing problems because of missing tor files or misconfigured "iptables". 
You can go here [https://www.torproject.org/docs/debian.html.en](url) and find out installing tor.
**Before that**
**Also check your iptables !** 
`sudo apt-get -purge remove iptables`
`sudo apt-get install iptables`
I think fixing iptables will work and you can route through anonsurf.

**Comment by piyushsharma08** [comment]
![screenshot from 2017-09-12 22-49-05](https://user-images.githubusercontent.com/22920938/30339445-a4edd988-980c-11e7-8a9f-246674be8f6a.png)

**Comment by yashaizen** [comment]
Oh seems like you have dependencies problems!
Try
`sudo apt-get -f install` 
Do these steps : 
`apt-get autoclean

apt-get -f install

dpkg --configure -a

apt-get -f install

apt-get -u dist-upgrade`
This will fix your dependencies issues.
The purge/remove option should not be used together. I have updated it above.
`sudo apt-get purge iptables` 
Since dependencies are fixed , shoot the command again:
`sudo apt-get install iptables`e3
Now you wont have any problems reinstalling iptables 👍

**Comment by thenano2001** [comment]
please help me im starting to use Kali linux and evrey time i try something new i always end up with a problem so can please anyone help me with thiss:





 root@mahfouz:~/Documents/kali-anonsurf# anonsurf start
 * killing dangerous applications
 * cleaning some dangerous cache elements
[ i ] Stopping IPv6 services:


[ i ] Starting anonymous mode:

 * Tor is not running!  starting it  for you

 * Saved iptables rules

 * Modified resolv.conf to use Tor and Private Internet Access DNS
 * All traffic was redirected through Tor

[ i ] You are under AnonSurf tunnel


root@mahfouz:~/Documents/kali-anonsurf# anonsurf myip

My ip is:

curl: (6) Could not resolve host: myexternalip.com



i tried everything nothing is working..if anybody can help me with this please help..thanks

**Comment by shaibaz200** [comment]
TRY this two lines :
sudo apt-get install ntpdate
press enter and 
sudo ntpdate -v pool.ntp.org
and again start anonsurf

**Comment by SumukhaPawar** [comment]
I got the same problem so help me please
[ i ] Starting anonymous mode:

    Tor is not running! starting it for you

    Saved iptables rules

    Modified resolv.conf to use Tor and Private Internet Access DNS

    All traffic was redirected through Tor

[ i ] You are under AnonSurf tunnel @

**Comment by fasetto** [comment]
> TRY this two lines :
> sudo apt-get install ntpdate
> press enter and
> sudo ntpdate -v pool.ntp.org
> and again start anonsurf

Thanks. It worked for me. (:

**Comment by maio122** [comment]
thanks
