### ISSUE TITLE
help start

### ISSUE THREAD

**Issue by derbiccp** [Und3rf10w/kali-anonsurf#4]
hi  
`root@debian:~#git clone https://github.com/Und3rf10w/kali-anonsurf.git
fatal: destination path 'kali-anonsurf' already exists and is not an empty directory.

root@debian:~/kali-anonsurf-master# ./installer.sh
0 upgraded, 0 newly installed, 0 to remove and 119 not upgraded.
dpkg: error: cannot access archive 'kali-anonsurf.deb': No such file or directory

root@debian:~/kali-anonsurf-master# anonsurf
bash: anonsurf: command not found

root@debian:~/kali-anonsurf-master# anonsurf start
bash: anonsurf: command not found
`  

Please!  how to fix

**Comment by Und3rf10w** [comment]
Without seeing what your actual folder structure and system looks like, try running the following commands:

```bash
rm -rf ~/kali-anonsurf*
cd ~
git clone https://github.com/Und3rf10w/kali-anonsurf.git
cd kali-anonsurf
chmod +x installer.sh
./installer.sh
```

This should start you with a clean slate, and perform the installation for you.

**Comment by Und3rf10w** [comment]
I'm gonna go ahead and close this for now. Please reopen this issue if you're still experiencing problems.

**Comment by minmyanmar45** [comment]
I make chmod +x installer.sh

but it's still showing the error message "atal: destination path 'kali-anonsurf' already exists and is not an empty directory."

**Comment by Und3rf10w** [comment]
Hi Minmyanar45,

Please open a new issue and try to avoid resurrecting old and closed issues unless it is directly relevant.

It looks like you already have a directory named ```kali-anonsurf```. Please remove that directory first, then clone a fresh copy and run the installer.
