### ISSUE TITLE
Operation not permitted for NMAP

### ISSUE THREAD

**Issue by gooddude33** [Und3rf10w/kali-anonsurf#44]
Hi,

I have started anonsurf and when trying to scan an external IP the following error gives out. I have tried adding the below two rules in Iptables but then i can only ping the host via nmap and the issue still persist. Please help

---------------------------------------------------------------------------------------------
Added rules
iptables -I OUTPUT -m state --state NEW,ESTABLISHED,RELATED,INVALID -j ACCEPT
iptables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
---------------------------------------------------------------------------------------------
NMAP result

root@kali:~# nmap destinationIP

Starting Nmap 7.60 ( https://nmap.org ) at 2017-09-14 02:29 EDT
sendto in send_ip_packet_sd: sendto(4, packet, 40, 0, destinationIP, 16) => Operation not permitted
Offending packet: TCP 192.168.221.128:63648 > destinationIP:80 A ttl=43 id=31185 iplen=40  seq=0 win=1024 
sendto in send_ip_packet_sd: sendto(4, packet, 40, 0, destinationIP, 16) => Operation not permitted
Offending packet: TCP 192.168.221.128:63649 > destinationIP:80 A ttl=43 id=55634 iplen=40  seq=0 win=1024 
Note: Host seems down. If it is really up, but blocking our ping probes, try -Pn
Nmap done: 1 IP address (0 hosts up) scanned in 3.75 seconds
root@kali:~#

**Comment by Und3rf10w** [comment]
I've actually written a blog post on this a few years ago. Tor will not support nmap scans unless they are of the TCP CONNECT type. Please refer to this blog-post for more info on this subject: https://und3rf10w.blogspot.com/2015/12/tor-nmap-scanning-and-esuring-they-fail.html
