### ISSUE TITLE
kali rolling 2

### ISSUE THREAD

**Issue by xrxrxr** [Und3rf10w/kali-anonsurf#8]
kali is now rolling and it use firefox ESR so it need to be changed

**Comment by Und3rf10w** [comment]
Good catch, I didn't even think about that. I'll get it fixed shortly.

**Comment by Und3rf10w** [comment]
It appears as though Kali upon upgrade symlinks ```iceweasel``` to ```firefox-esr```. Regardless, I'll change it to use ```firefox-esr``` to prevent future issues.

**Comment by Und3rf10w** [comment]
Fixed by 91d681a

**Comment by xrxrxr** [comment]
Thanks à lot :)
